Fail registry pruning script early if API call fails
Previously, a failure in the openshift_tag_whitelist script would be
silently ignored, which could lead to some protected container images
being removed.i

This commit changes the way we are generating the whitelist, by checking
the output of each dlrnapi call and exiting if there is any failure.
Then, the openshift_registry_pruner script will detect that and fail
early, before trying to remove any tags.

This also gives us an optimization for the non-failure case, where we
only call openstack_tag_whitelist once, instead of once per namespace.

Change-Id: Ica9dada4817fb114721c9ab133f76d863abf3821

diff --git a/roles/rdo-infra/registry-image-pruning/templates/openshift_registry_pruner.sh.j2 b/roles/rdo-infra/registry-image-pruning/templates/openshift_registry_pruner.sh.j2
--- a/roles/rdo-infra/registry-image-pruning/templates/openshift_registry_pruner.sh.j2
+++ b/roles/rdo-infra/registry-image-pruning/templates/openshift_registry_pruner.sh.j2
@@ -5,8 +5,14 @@
 oc login -u system:admin --config=/etc/origin/master/admin.kubeconfig
 oc adm config use-context default/{{ openshift_master_cluster_hostname | replace('.','-') }}:8443/system:admin
 
+keeplist=$(/usr/local/bin/openshift_tag_whitelist)
+if [ $? -ne 0 ]; then
+  echo "Failed to generate tag whitelist, stopping"
+  exit 1
+fi
+
 {% for ns in pruner_namespaces %}
-/usr/local/bin/openshift_tag_pruner --days {{ ns.pruner_days | default(pruner_days | default ('3')) }} --whitelist "$(/usr/local/bin/openshift_tag_whitelist)" {{ ns.name }} --confirm
+/usr/local/bin/openshift_tag_pruner --days {{ ns.pruner_days | default(pruner_days | default ('3')) }} --whitelist "${keeplist}" {{ ns.name }} --confirm
 {% endfor %}
 
 # Pruning is done with the rdo.pruner user
